### ISSUE TITLE
Save dataset

### ISSUE THREAD

**Issue by truc-h-nguyen** [truc-h-nguyen/Toddler-activity-suggestions#7]
@nickvazz 
Hi Nick, 
In [[16]](https://github.com/truc-h-nguyen/Toddler-activity-suggestions/blob/main/B_Save_object_datasets_from_COCO.ipynb),  I couldn't download another dataset if the "data" folder is already occupied.

The "bowl" set has about 7k entries while the "teddy bear" set has about 2k. I take number of samples for "bowl" train set is 2000. Can I take 1000 samples for "teddy bear" train set or the number of samples of both train sets need to be the same?

**Comment by nickvazz** [comment]
Ideally you have the same number of samples for each class, but there are ways to deal with an imbalanced dataset
