### ISSUE TITLE
Update 11/09/21

### ISSUE THREAD

**Issue by truc-h-nguyen** [truc-h-nguyen/Toddler-activity-suggestions#9]
@nickvazz 
Hi Nick,
May you check for me the last two lines [here](https://github.com/truc-h-nguyen/Toddler-activity-suggestions/blob/main/C_Image_augmentation.ipynb)?
I've already set seed, but why does it still create a new list? 
Thank you very much!

**Comment by nickvazz** [comment]
It looks like you would need to make a copy of the list then shuffle with the seed to get the same results

**Comment by nickvazz** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/8573886/141225014-546a5bf7-f28d-45d7-894e-98491c363545.png">
